/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function crc64Sync(input: string | Buffer): string
export declare class Crc64 {
  constructor()
  /** Class method */
  update(input: string | Buffer): void
  sum(): string
}
